crypto/libntrup/src/ref/r3_recip.c, crypto/libntrup/src/ref/rq_recip3.c, include/llarp/handlers/tun.hpp, include/llarp/ip.hpp, include/llarp/threading.hpp, include/tuntap.h, llarp/ev.hpp, llarp/ev_kqueue.hpp, llarp/ev_win32.hpp, llarp/handlers/tun.cpp, llarp/ip.cpp, llarp/win32_inet.c, llarp/win32_intrnl.c, vendor/libtuntap-master/tuntap-unix-bsd.c, vendor/libtuntap-master/tuntap-unix-freebsd.c, vendor/libtuntap-master/tuntap-unix-sunos.c
bsd tuntap kinda works, still debugging it
-rick
=> implement tuntap on BSD

LICENSE, crypto/libntrup/src/avx/mult.c, crypto/libntrup/src/avx/rq.c, crypto/libntrup/src/avx/rq_mod3.c, daemon/main.cpp, include/llarp/pathset.hpp, include/tuntap.h, llarp/dnsd.cpp, llarp/ev.cpp, llarp/ev.hpp, llarp/ev_kqueue.hpp, llarp/ev_win32.hpp, llarp/handlers/tun.cpp, llarp/link/utp.cpp, llarp/time.cpp, readme.md, vendor/libtuntap-master/tuntap-windows.c, vendor/libtuntap-master/tuntap.cpp
wooooo
welp time to start debugging 👌🏻
=> it sorta works on windows now

include/llarp/ip.hpp, llarp/handlers/tun.cpp, llarp/ip.cpp
had some stuff unfinished yesterday
=> ip: some fixes and tweaks

llarp/ip.cpp
=> ip: fix UDP checksum offset

include/llarp/ip.hpp, include/llarp/net.hpp, llarp/ip.cpp
shouldn't change current logic of anything
=> some tweaks and optimizations, {h,n}uint16_t types

daemon/main.cpp, include/llarp/dnsd.hpp, include/llarp/net.hpp, llarp/arpc.cpp, llarp/dns.cpp, llarp/dnsc.cpp, llarp/dnsd.cpp, llarp/handlers/tun.cpp, llarp/ip.cpp
one's complement math is pretty fun
=> ip: make things fragmentation-aware, cleanup UDP handling; also format

include/llarp/dns.hpp, include/tuntap.h, llarp/dnsc.cpp, llarp/dnsd.cpp, llarp/ev_win32.hpp, llarp/router.cpp, llarp/threadpool.cpp, vendor/libtuntap-master/tuntap-windows.c, vendor/libtuntap-master/tuntap.cpp
this also fixes a bug where the public inet4 and private inet4 addresses would be written to a RC
=> fix win32 event loop

include/llarp/address_info.hpp, include/llarp/bencode.hpp, include/llarp/dht/message.hpp, include/llarp/dht/messages/findintro.hpp, include/llarp/dht/messages/findrouter.hpp, include/llarp/dht/messages/gotintro.hpp, include/llarp/dht/messages/gotrouter.hpp, include/llarp/dht/messages/pubintro.hpp, include/llarp/exit_info.hpp, include/llarp/messages/dht.hpp, include/llarp/messages/discard.hpp, include/llarp/messages/path_confirm.hpp, include/llarp/messages/path_latency.hpp, include/llarp/messages/path_transfer.hpp, include/llarp/pow.hpp, include/llarp/profiling.hpp, include/llarp/router_contact.hpp, include/llarp/service/Identity.hpp, include/llarp/service/Info.hpp, include/llarp/service/Intro.hpp, include/llarp/service/IntroSet.hpp, include/llarp/service/protocol.hpp
This specifies the leaf nodes of the inheritance hierarchy.
=> Specify override and final in inheritance tree of llarp::IBEncodeMessage

Makefile
=> remove DNS_PORT

llarp/ev_kqueue.hpp, llarp/rpc.cpp, test/test_llarp_queue.cpp, test/test_llarp_queue_manager.cpp
=> Minor fixes for builds

docker/ubuntu.Dockerfile
helpful in trying to reproduce #74
=> Create dockerfile for ubuntu

include/llarp/aligned.hpp, include/llarp/exit/endpoint.hpp, include/llarp/handlers/exit.hpp, include/llarp/service/Info.hpp, llarp/exit/endpoint.cpp, llarp/handlers/exit.cpp, llarp/service.cpp
* have exit pick better paths for down stream traffic
* set vanity nonce in service info when provided by private keys
=> Various changes

include/llarp/handlers/tun.hpp, llarp/ev.hpp
Add the overrides, add a header.
=> Minor build fixes

include/llarp/nodedb.hpp, llarp/context.cpp, llarp/dht/find_router.cpp, llarp/exit/session.cpp, llarp/nodedb.cpp, llarp/pathbuilder.cpp, llarp/router.cpp, llarp/service/endpoint.cpp
Remove a lot of crufty C-style stuff. One step closer to making the event loop fully RAII.
=> Convert llarp_nodedb to be a true C++ class

CMakeLists.txt, llarp/ev.hpp, llarp/ev_kqueue.hpp
i'm an idiot
(fixes #134)
also cleaned up cmakelists
=> fix hardwired unix size

llarp/dht/context.cpp, llarp/router.cpp
Makes sure router mode actually can connect out to remote nodes
Adjust DHT minimum connected nodes to work at any size for now (but never use more than 4?) and output debug
=> Fix issues with running your own private test net

llarp/exit/session.cpp, llarp/exit/session.hpp, llarp/handlers/exit.cpp, llarp/handlers/tun.cpp, llarp/service/endpoint.cpp
this makes tcp streams freak out less
=> order downstream packets

llarp/router.cpp, llarp/router_contact.cpp, llarp/router_contact.hpp, llarp/version.cpp, llarp/version.hpp, test/test_router_contact.cpp
set `NetID::DefaultValue` statically. Tidy up some more code along the way.
=> Fix RCTest.TestSignVerify

llarp/dns/dns.hpp, llarp/dns/server.hpp, llarp/exit/endpoint.cpp, llarp/handlers/exit.cpp, llarp/handlers/exit.hpp, llarp/handlers/tun.cpp, llarp/handlers/tun.hpp, llarp/nodedb.cpp, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp
- Remove unreachable code
- Add a header guard
- Change a repeated copy to a move
=> Fix some low hanging performance issues

CMakeLists.txt, llarp/bencode.cpp, llarp/bencode.h, llarp/bencode.hpp, llarp/buffer.h, llarp/buffer.hpp, llarp/dht/message.hpp, test/test_llarp_aligned.cpp, test/test_llarp_bencode.cpp, vendor/libtuntap-master/tuntap-unix-darwin.c
I reordered the file to group operations together.
=> Add test suite for bencode

CMakeLists.txt, llarp/crypto/types.cpp, test/crypto/test_llarp_crypto_types.cpp, test/test_llarp_router.cpp, test/test_util.cpp, test/test_util.hpp
this builds on top of #222 and #223, last commit is the only relevant one.
=>  Add tests for crypto/types

contrib/cluster-shell/init.sh
one more idea, sorry for all the extra metadata
=> add cluster-shell initialize script

docs/old-wire-protocol.txt, llarp/handlers/tun.cpp, llarp/link/utp_internal.hpp, llarp/path/path.cpp, llarp/path/pathbuilder.cpp, llarp/path/pathbuilder.hpp, llarp/path/pathset.cpp, llarp/path/pathset.hpp, llarp/service/endpoint.cpp
*  lower utp fragment size by 512 bytes
* backport crash fix from master
=> lower utp fragment size by 512 bytes

Makefile
add ninja build option to makefile such that you can run:
`$ make NINJA=$(which ninja)`
and it will use ninja to build
please note that to install after building with ninja you need to run:
`$ make NINJA=$(which ninja) install`
=> add ninja build option

readme.md
Move usage to the top of the readme, it was pretty hidden at the bottom before
=> Move usage

CMakeLists.txt, llarp/CMakeLists.txt, llarp/link/server.cpp, llarp/link/server.hpp, llarp/link/session.hpp, llarp/link/utp.cpp, llarp/link/utp_internal.hpp, llarp/router/abstractrouter.hpp, llarp/router/router.cpp, llarp/router/router.hpp, llarp/rpc/rpc.cpp
* make rpc compile right
* make link sessions introspectable
* make utp write buffers fully flush each tick
=> merge staging

CMakeLists.txt, libabyss/include/abyss/client.hpp, libabyss/include/abyss/http.hpp, libabyss/include/abyss/server.hpp, libabyss/main.cpp, libabyss/src/client.cpp, libabyss/src/server.cpp, llarp/CMakeLists.txt, llarp/link/iwp_internal.hpp, llarp/rpc/rpc.cpp, llarp/util/json.cpp, llarp/util/json.hpp, llarp/util/status.hpp, test/test_libabyss.cpp
This breaks the cyclic dependency between libabyss and llarp
=> Move abyss/json to llarp/util/json

llarp/service/tag.hpp
=> unbreak dht

llarp/dht/messages/findrouter.cpp
aaaaaaaaaaaAAAAAAAAAaAAAAAAAAAAA (this should fix broken staging a bit)
=> ONLY CHECK FOR ACTIVE DHT NODES

llarp/ev/ev.hpp
=> Add missing override in evp.hpp

llarp/ev/ev_epoll.cpp
fixes build with gcc 6 which debian uses
=> don't inline shit

llarp/CMakeLists.txt, llarp/crypto/crypto_libsodium.cpp, llarp/crypto/ec.cpp, llarp/crypto/ec.hpp, llarp/crypto/types.cpp, llarp/crypto/types.hpp
use lokid's signature algorithm so that public keys match up.
=> change signing algo

CMakeLists.txt, llarp/ev/ev_win32.cpp, ui-win32/UIMain.Designer.cs, vendor/libtuntap-master/tuntap-windows.c, win32-setup/lokinet-win32.iss
also bring the interface up _before_ faking a DHCP offer
=> do not conflict with any existing TAP ifs on windows

ui-win32/AboutBox.Designer.cs, ui-win32/UIMain.Designer.cs, ui-win32/UIMain.cs, ui-win32/UIMain.resx
=> make the coreclr/mono ui tray icon do something

llarp/path/pathbuilder.cpp, llarp/router/router.cpp
path building more robust selection
=> have service nodes maintain min connections

llarp/ev/ev.cpp
different symbols
@majestrate poke
=> winsock2 nit

llarp/net/net_int.hpp, llarp/util/bencode.cpp
=> fix bencode read crash with empty buffer

llarp/util/metrics_publishers.cpp
Fixes #458 
I think this might be the root cause. And it won't hurt either way.
=> Flush output stream after publish

readme.md
Duplicate docs to start of readme, to make more visible
=> Duplicate docs

CMakeLists.txt, llarp/util/object.hpp, test/util/test_llarp_util_object.cpp
Got to 10,000 iterations of the test with no failure. UBSAN grabbed the initial failure fairly easily.
=> Fix Catalog.Iterator test failure

Makefile, lokinet-bootstrap
dont run unittest with CROSS=ON
=> use fixed path for lokinet-bootstrap

llarp/path/pathbuilder.cpp, llarp/router/router.cpp
* only use good routers for first hops
* don't have service nodes kill bad RCs
=> prevent peer exaustion

llarp/util/win32_logger.cpp, llarp/util/win32_logger.hpp
need to be able to write into these all the time
just promote to internal file scope and call it a day
=> move these into a read-write data segment

llarp/util/bencode.cpp
wouldn't be surprised if all the BSDs did this
=> fix warning

contrib/testnet/genconf.py, llarp/dht/context.hpp, llarp/dht/recursiverouterlookup.cpp, llarp/dht/recursiverouterlookup.hpp, test/dht/mock_context.hpp
* fix up integration tests
* make recursive router lookup backtrack
=> fix integration tests

llarp/profiling.cpp, llarp/profiling.hpp, llarp/router/router.cpp, llarp/service/endpoint.cpp, llarp/utp/session.cpp
* refactor profiling function names
* remove instances of profiling that dont make sense
* utp link layer make ping less active, pre-emptive pump faster
=> qol improvements

docs/proto_v0.txt, llarp/crypto/encrypted_frame.hpp, llarp/dht/messages/findrouter.cpp, llarp/exit/session.cpp, llarp/exit/session.hpp, llarp/messages/relay_commit.cpp, llarp/messages/relay_commit.hpp, llarp/nodedb.cpp, llarp/nodedb.hpp, llarp/path/pathbuilder.cpp, llarp/path/pathbuilder.hpp, llarp/router/abstractrouter.hpp, llarp/router/router.hpp, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp, llarp/util/logic.cpp, llarp/util/logic.hpp, llarp/util/threadpool.h
=> bundle RC in build record to improve build success rates.

CMakeLists.txt
fixes the stuff left over from the last PR
=> fix windows

llarp/ev/ev_kqueue.cpp
=> fix issue #550 kqueue crash

daemon/main.cpp
```
$ lokinet -h
Lokinet is a private, decentralized and IP based overlay network for the internet
Usage:
lokinet [OPTION...] positional parameters
-v, --verbose     Verbose
-h, --help        help
-g, --generate    generate config
-r, --router      run as router
-f, --force       overwrite
--config arg  path to configuration file
```
=> Make help more useful

llarp/dns/name.cpp, llarp/dns/name.hpp, llarp/dns/question.cpp, llarp/dns/question.hpp, llarp/handlers/exit.cpp, llarp/handlers/tun.cpp, llarp/service/address.cpp, llarp/service/address.hpp, llarp/util/encode.hpp, test/service/test_llarp_service_address.cpp
enables using subdomains on loki and snode addresses
also adds some unit tests
=> fix Issue 563

contrib/node-monitor/README.md, contrib/node-monitor/ini.js, contrib/node-monitor/lokinet.js, contrib/node-monitor/monitor_client.js, contrib/node-monitor/package-lock.json, contrib/node-monitor/package.json
after building lokinet
cd contrib/node-monitor
npm install
npm start
and wait 30s for final score
=> contrib: lokinet monitor

llarp/hook/ihook.hpp, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp, llarp/service/endpoint_util.cpp, llarp/service/endpoint_util.hpp, llarp/util/status.hpp
More work from my branch of testing + tidying `service::Endpoint`.
=> Tidy up service endpoint a bit more

llarp/service/context.cpp, llarp/service/endpoint.cpp, llarp/service/identity.cpp, llarp/service/identity.hpp, test/service/test_llarp_service_identity.cpp, test/test_util.hpp
=> More explicit error when keyfile is not a valid file

CMakeLists.txt, llarp/router/router.cpp, llarp/util/alloc.hpp, llarp/util/logger_internal.hpp
I suspect this was broken in part by #570
=> Fix ASAN build

contrib/munin/lokinet-munin.py, contrib/node-monitor/ini.js, contrib/node-monitor/lokinet.js, contrib/node-monitor/monitor_client.js, contrib/shadow/genconf.py
my editor has also formatted this to some cleaner (❓) standard
=> Minor warnings fixes in python/javascript code

llarp/handlers/tun.cpp, llarp/path/path.hpp, llarp/service/outbound_context.cpp
also make code more DRY and make format
=> double path build timeout from 15s to 30s

contrib/py/pylokinet/pylokinet/instance.py, daemon/main.cpp, include/llarp.h, include/llarp.hpp, llarp/CMakeLists.txt, llarp/context.cpp, llarp/crypto/crypto_noop.cpp, llarp/crypto/crypto_noop.hpp, llarp/util/buffer.hpp, test/link/test_llarp_link.cpp
I suspect we can iterate on this reasonably easily.
Interestingly, running this and trying to connect to the main net (obviously) doesn't work, but the error/warning messages you get are not obvious:
```
[NFO] (465) Wed May 29 09:51:04 2019 BST router/router.cpp:1298	We need at least 4 service nodes to build paths but we have 1 in nodedb
[NFO] (465) Wed May 29 09:51:04 2019 BST router/router.cpp:1313	connecting to 2 random routers to keep alive
[NFO] (465) Wed May 29 09:51:04 2019 BST router/router.cpp:1869	connecting to 0 out of 2 random routers
[NFO] (465) Wed May 29 09:51:04 2019 BST router/router.cpp:1869	connecting to 0 out of 1 random routers
[NFO] (465) Wed May 29 09:51:04 2019 BST router/router.cpp:1869	connecting to 0 out of 1 random routers
[NFO] (465) Wed May 29 09:51:04 2019 …
```
=> Initial No-Op Crypto implementation

contrib/munin/lokinet-munin.py, docs/dht_v0.txt, llarp/iwp/linklayer.cpp, llarp/link/server.cpp, llarp/messages/relay_commit.hpp, llarp/path/path.cpp, llarp/path/pathbuilder.cpp, llarp/path/pathset.cpp, llarp/router/abstractrouter.cpp, llarp/router/abstractrouter.hpp, llarp/router/router.cpp, llarp/router/router.hpp, llarp/rpc/rpc.cpp, llarp/service/context.cpp, llarp/utp/linklayer.cpp, llarp/utp/session.cpp
* fix up munin
* update docs
* explicitly close link layer sessions on timeout
* set default path lifetime in path builds
* change priority of link layer sessions when sending
* remove ips from rpc call
* always close utp socket on close
=> recent stability stuff

libutp/utp_internal.h
=> revert modification to libutp

llarp/CMakeLists.txt, llarp/dnsc.cpp, llarp/handlers/exit.cpp, llarp/messages/link_message.cpp, llarp/metrics/metrictank_publisher.cpp, llarp/metrics/publishers.cpp, llarp/router/router.cpp, llarp/util/metrics.hpp, llarp/util/metrics_core.cpp, llarp/util/metrics_core.hpp, llarp/util/metrics_types.cpp, llarp/util/metrics_types.hpp, llarp/util/printer.hpp, llarp/utp/session.cpp, test/metrics/test_llarp_metrics_publisher.cpp, test/util/test_llarp_util_metrics_core.cpp, test/util/test_llarp_util_metrics_types.cpp
some fun template stuff, output looks like:
```
2019-06-13T23:09:29.671754+01:00 9 Records
Elapsed Time: 60.0033s
DHTImmediate.RX [
[ [ [ "id" [ "j99u484qf9n9b5jsjpgktojyxnyjbtuiqew1zqqt4zr4nq86bxky.snode" ] ] ] ] count = 9, total = 9, min = 1, max = 1
[ [ [ "id" [ "nc9y88xsr7cqmpytc6tbo5dbf5c9fa3is5dezmdwxwgfkuhemg3o.snode" ] ] ] ] count = 6, total = 6, min = 1, max = 1
]
DHTImmediate.to [
[ [ [ "tx" [ "j99u484qf9n9b5jsjpgktojyxnyjbtuiqew1zqqt4zr4nq86bxky.snode" ] ] ] ] count = 8, total = 8, min = 1, max = 1
[ [ [ "tx" [ "nc9y88xsr7cqmpytc6tbo5dbf5c9fa3is5dezmdwxwgfkuhemg3o.snode" ] ] ] ] count = 6, total = 6, min = 1, max = 1
]
RelayCommit.to [
[ [ [ "tx" [ "j99u484qf9n9b5jsjpgktojyxnyjbtuiqew1zqqt4zr4nq86bxky.snode" ] ] ] ] count = 5, total = 5, min = 1, max = 1
]
RelayDownstream.RX [ …
```
=> Tagged metric rework

llarp/context.cpp, llarp/metrics/metrictank_publisher.cpp
also don't send username, set nickname from config instead.
=> Send netid to metrictank

llarp/exit/session.cpp, llarp/path/path.hpp, llarp/path/pathbuilder.cpp, llarp/path/pathbuilder.hpp, llarp/path/pathset.hpp, llarp/service/endpoint.cpp, llarp/service/outbound_context.cpp
Pathbuilding doesn't (directly) depend on the DHT.
=> Tidy up pathbuilder code

CMakeLists.txt, cmake/unix.cmake, llarp/CMakeLists.txt, llarp/config.cpp, llarp/crypto/types.cpp, llarp/nodedb.cpp, llarp/nodedb.hpp, llarp/profiling.cpp, llarp/router_contact.cpp, llarp/service/identity.cpp, llarp/util/bencode.hpp, llarp/util/fs.cpp, llarp/util/fs.hpp, llarp/util/threadpool.h
=> Fix issue #17

readme.md
make gitlab start building again
=> Gitlab ci fix

vendor/cppbackport-master/lib/fs/path.h
https://en.cppreference.com/w/cpp/filesystem/path/path <- use one of these
=> Add missing cppbackport fs::path constructor

llarp/util/threading.cpp
this SHOULD fix the freebsd build that was broken by #689
=> fix freebsd build

llarp/metrics/json_publisher.cpp, llarp/path/path.cpp
compiler upgrade(?) broke my docker build.
=> Fixup two minor warnings

llarp/config/config.cpp, llarp/config/config.hpp, llarp/router/router.cpp, llarp/router/router.hpp, vendor/cppbackport-master/lib/fs/path.cpp, vendor/cppbackport-master/lib/fs/path.h
=> Fix config application

CMakeLists.txt, cmake/FindLibUV.cmake, cmake/unix.cmake, libabyss/CMakeLists.txt, llarp/ev/ev_libuv.hpp
=> Add FindLibUV and migrate to use it

llarp/context.cpp, llarp/dht/context.cpp, llarp/nodedb.cpp, llarp/router/router.cpp, llarp/router/router.hpp, llarp/router_contact.cpp, llarp/router_contact.hpp
this makes the network be able to bootstrap again
also fixes some parts in network exploration
=> Fix bootstraping

readme.md, readme_es.md
This edit is to add a link to the spanish translation of readme.md
=> Update readme.md to include readme_es.md link

llarp/dht/context.cpp, llarp/dht/explorenetworkjob.cpp, llarp/dht/key.hpp, llarp/dht/message.cpp, llarp/dht/tx.hpp, llarp/nodedb.cpp, llarp/router/router.cpp
reduce verbosity of default logging
=> reduce logging

llarp/ev/ev_libuv.cpp, llarp/exit/session.cpp, llarp/handlers/tun.cpp, llarp/path/pathbuilder.cpp, llarp/path/pathset.cpp, llarp/path/pathset.hpp, llarp/service/endpoint.cpp, llarp/service/endpoint_state.cpp, llarp/service/endpoint_state.hpp, llarp/service/outbound_context.cpp, llarp/service/protocol.hpp, llarp/service/sendcontext.cpp, llarp/utp/linklayer.cpp, llarp/utp/session.cpp, llarp/utp/session.hpp
=> Make hop length and quantity configurable

contrib/testnet/genconf.py, llarp/dht/context.cpp, llarp/dht/context.hpp, llarp/dht/messages/findrouter.cpp, llarp/dht/recursiverouterlookup.cpp, llarp/ev/ev_libuv.cpp, llarp/exit/session.cpp, llarp/handlers/tun.cpp, llarp/path/pathbuilder.cpp, llarp/path/pathset.cpp, llarp/path/pathset.hpp, llarp/service/endpoint.cpp, llarp/service/endpoint_state.cpp, llarp/service/endpoint_state.hpp, llarp/service/outbound_context.cpp, llarp/service/protocol.hpp, llarp/service/sendcontext.cpp, llarp/utp/linklayer.cpp, llarp/utp/session.cpp, llarp/utp/session.hpp, test/dht/mock_context.hpp
builds on #720 
makes RCs propagate better in DHT.
=> handle dht case

docs/spanish/LICENSE, docs/spanish/README, docs/spanish/vision-general.txt
From time to time I will translate this dirctory to spanish.
I would use a pseudo academic and formal enough style with some literal and some cultural translation.
Strict spellcheck.
=> Basic docs translations to spanish, more to go later

daemon/main.cpp
this would allow in the future final clean up tasks to fire.
=> run main in it's own thread and set its process name.

.travis.yml
https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
=> Use travis_wait because builds/linkers are slow

include/tuntap.h, llarp/ev/ev_libuv.cpp, llarp/path/path.cpp, llarp/path/path_context.cpp, llarp/path/path_context.hpp, llarp/router/outbound_message_handler.hpp, llarp/router/outbound_session_maker.hpp, llarp/router/rc_lookup_handler.hpp, llarp/service/endpoint_state.hpp, llarp/service/protocol.cpp, llarp/util/metrics_core.cpp, llarp/util/metrics_core.hpp, llarp/util/metrics_types.hpp
*probably* fix thread safety. fixes #753
=> Fix metrics thread safety

docker/compose/bootstrap.Dockerfile, docker/compose/bootstrap.ini, docker/compose/docker-compose.yml, docker/compose/router.Dockerfile, docker/compose/router.ini
to build and run every:
```
$ docker-compose -f ./docker/compose/docker-compose.yml --project-directory . up --scale router=10
```
will start 1 bootstrap and 10 normal nodes.
=> WIP on docker-compose workflow

.travis.yml, Makefile
What @jagerman wants, @jagerman gets. fixes #727
=> CI to catch missing `make format`

.travis.yml
=> Test make windows on macOS, and avoid timeouts

vendor/cxxopts/CMakeLists.txt
```
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Installing: /usr/local/bin/lokinet
-- Installing: /usr/local/bin/lokinet-rcutil
-- Up-to-date: /usr/local/bin/lokinet-bootstrap
```
=> Fix make install

docker/compose/bootstrap.Dockerfile, docker/compose/compose-base.Dockerfile, docker/compose/docker-compose.yml, docker/compose/router.Dockerfile
This still doesn't work. but it doesn't work quite as much as the previous version.
=> docker-compose fixes

llarp/config/config.cpp
`\n` is 11 fewer characters than ` << std::endl`
=> replace endl with '\n in config.cpp

llarp/router_contact.cpp
=> disable rc expiration

llarp/constants/version.hpp, motto.txt
=> bump version and motto

ui-macos/lokinet.xcodeproj/project.pbxproj, ui-macos/lokinet.xcodeproj/project.xcworkspace/contents.xcworkspacedata
=> Use a hardened build for macOS release

daemon/main.cpp
=> Add a --version flag to lokinet CLI args

llarp/link/server.cpp, llarp/net/net.cpp
=> Fix issue 865

llarp/iwp/iwp.cpp, llarp/iwp/iwp.hpp, llarp/iwp/linklayer.cpp, llarp/iwp/linklayer.hpp, llarp/iwp/session.cpp, llarp/link/factory.hpp, llarp/link/server.cpp, llarp/link/server.hpp, llarp/router/router.cpp, test/link/test_llarp_link.cpp
@jagerman rebuild debs and redeploy once merged
=> pump to upper layers every time we decrypt link layer traffic

llarp/ev/ev.hpp, llarp/ev/ev_libuv.cpp, llarp/ev/ev_libuv.hpp, llarp/path/path.cpp, llarp/path/path.hpp, llarp/path/path_context.cpp, llarp/path/pathbuilder.cpp, llarp/path/pathset.cpp, llarp/path/pathset.hpp, llarp/router/router.cpp, llarp/router/router.hpp, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp, llarp/service/intro.cpp, llarp/util/time.cpp, llarp/util/time.hpp
after this commit is merged dev should be building paths correctly
=> make path builds work

llarp/ev/ev.cpp, llarp/ev/ev.hpp, llarp/iwp/session.cpp, llarp/messages/discard.hpp, llarp/path/pathset.hpp, llarp/service/info.cpp, llarp/service/info.hpp, llarp/util/thread/logic.cpp, llarp/util/thread/logic.hpp, llarp/util/thread/threadpool.cpp, llarp/util/thread/threadpool.h, llarp/util/thread/timer.cpp, llarp/util/thread/timer.hpp, test/link/test_llarp_link.cpp
the logic thread seemed to work in a way that was different from the way i remember it should.
fixed.
=> fix logic thread behavior

daemon/main.cpp, llarp/CMakeLists.txt, llarp/config/config.cpp, llarp/ev/ev_win32.cpp, llarp/util/lokinet_init.c, llarp/util/lokinet_init.h, ui-win32/Properties/AssemblyInfo.cs, ui-win32/dlgBootstrap.Designer.cs, ui-win32/dlgBootstrap.resx
this was tested on [wine 4.4](https://github.com/OpenIndiana/oi-userland/pull/5124) running on solaris 11 `snv_151` at rev https://github.com/illumos/illumos-gate/commit/fec6629365dbee0f183b4616a0aa43667bc8838c
this is also a PR for all the last-minute win32 patches to go into lokinet v0.6-RELEASE
=> win32 fixes

llarp/config/key_manager.cpp, llarp/config/key_manager.hpp, llarp/iwp/linklayer.hpp, llarp/router/router.cpp, llarp/router/router.hpp
=> Key management cleanup

llarp/ev/ev_libuv.cpp, llarp/iwp/message_buffer.cpp, llarp/iwp/session.cpp, llarp/link/i_link_manager.hpp, llarp/link/link_manager.cpp, llarp/link/link_manager.hpp, llarp/link/server.hpp, llarp/path/path_context.cpp, llarp/path/path_context.hpp, llarp/router/router.cpp, llarp/util/thread/logic.cpp
includes:
* break the world iwp changes
* path resource leak fix
* connection limiting
=> last changes before 0.6.0 version bump

llarp/config/key_manager.cpp, llarp/config/key_manager.hpp, llarp/router/router.cpp
Small fix to initialize the KeyManager before the inbound links
=> Key manager fixes

CMakeLists.txt, daemon/main.cpp, include/llarp.hpp, llarp/context.cpp, llarp/router/abstractrouter.hpp, llarp/router/router.cpp, llarp/router/router.hpp, llarp/util/bencode.cpp, llarp/util/thread/threading.hpp, llarp/util/thread/timer.cpp
calling `Router::Tick` can potentially lock stuff up if called this way. (i think)
=> try fixing router lockup

llarp/handlers/tun.cpp, llarp/util/aligned.hpp
=> reduce cpu use in logic thread

llarp/iwp/message_buffer.cpp, llarp/iwp/session.hpp, llarp/service/info.cpp, llarp/service/info.hpp
reduces traffic overhead from retransmissions between nodes.
=> increase ack window

lokinet-bootstrap
- Added new URLs for mainnet/testnet
- Make curl fail on HTTP error responses (like 404)
=> Bootstrap changes

.gitlab-ci.yml
change to xenial
add debug/release versions
include lokinetctl
use ninja like travis
disable freebsd (due to newer dependencies)
=> try to fix gitlab CI (redo 991)

llarp/config/config.cpp
This is needed for a decent UX with the GUI
=> Enable the JSON RPC API by default

include/llarp.h, llarp/ev/ev.h, llarp/nodedb.hpp
=> no more MSVC builds pls

llarp/constants/version.h, motto.txt
=> 0.6.1 version bump

lokinet-bootstrap
This OS is worse than Windows. :(
=> Fix for macos's decrepit old bash 3.x

llarp/exit/session.cpp
this makes snode sessions expire after not being used for a while
=> Expire snode sessions based off activity 

llarp/dht/context.cpp, llarp/dht/txholder.hpp, llarp/service/lookup.hpp
* remove stupid template parameter for timeout
* make dht lookup variable on runtime
* make dht timeouts properly asymmetric
=> dht timeout tweak

contrib/testnet/genconf.py, llarp/context.cpp, llarp/dht/context.cpp, llarp/dht/localrouterlookup.cpp, llarp/dht/messages/findrouter.cpp, llarp/dht/messages/gotrouter.cpp, llarp/dht/messages/gotrouter.hpp, llarp/dht/recursiverouterlookup.cpp, llarp/dht/txholder.hpp, llarp/nodedb.cpp, llarp/nodedb.hpp, llarp/path/path_context.cpp, llarp/router/i_rc_lookup_handler.hpp, llarp/router/rc_lookup_handler.cpp, llarp/router/rc_lookup_handler.hpp, llarp/router/router.cpp, llarp/router_contact.cpp, llarp/service/endpoint.cpp
this makes path build not suck and allows the network to full mesh
=> disable iterative behavior in DHT

contrib/testnet/genconf.py, llarp/context.cpp, llarp/dht/context.cpp, llarp/dht/localrouterlookup.cpp, llarp/dht/messages/findrouter.cpp, llarp/dht/messages/gotrouter.cpp, llarp/dht/messages/gotrouter.hpp, llarp/dht/recursiverouterlookup.cpp, llarp/dht/txholder.hpp, llarp/nodedb.cpp, llarp/nodedb.hpp, llarp/path/path_context.cpp, llarp/router/i_rc_lookup_handler.hpp, llarp/router/rc_lookup_handler.cpp, llarp/router/rc_lookup_handler.hpp, llarp/router/router.cpp, llarp/router_contact.cpp, llarp/service/endpoint.cpp
=> Dht fixes cleanup

llarp/rpc/rpc.cpp
Only the port was being used, the IP was being ignored and it was always
binding to localhost.
=> Fix json api bind IP

llarp/constants/version.h
for relay fixes only
(we do not need to merge #1046 yet for 0.6.4 imo)
=> bump version for 0.6.4

llarp/rpc/rpc.cpp
If we pass the last block hash to lokid it can give us an "unchanged" response instead of the service node states to tell us that there is no updated needed.
Separated into two commits: the first one doesn't change any logic, but makes the second one much easier to read.
=> Add support for lokid's "unchanged" response

llarp/router/abstractrouter.cpp, llarp/router/abstractrouter.hpp
=> Remove dead code (AbstractRouter::EnsureRouter())

llarp/dht/context.cpp, llarp/dht/context.hpp, llarp/dht/messages/findintro.cpp, llarp/dht/messages/findintro.hpp, llarp/dht/messages/findrouter.cpp, llarp/dht/messages/findrouter.hpp, llarp/dht/messages/gotintro.cpp, llarp/dht/messages/gotintro.hpp, llarp/dht/messages/gotrouter.cpp, llarp/dht/messages/gotrouter.hpp, llarp/dht/messages/pubintro.cpp, llarp/dht/messages/pubintro.hpp, llarp/dht/recursiverouterlookup.cpp, llarp/nodedb.cpp, llarp/nodedb.hpp, llarp/router/abstractrouter.cpp, llarp/service/endpoint.cpp, llarp/service/hidden_service_address_lookup.cpp, test/dht/mock_context.hpp, test/dht/test_llarp_dht_serviceaddresslookup.cpp, test/dht/test_llarp_dht_taglookup.cpp
=> Refactor single char variables in dht messages

CMakeLists.txt, llarp/ev/ev_libuv.cpp, llarp/util/time.cpp, llarp/util/time.hpp
=> make all timestamps monotonic and run loopback testnet at 1/5 speed

llarp/CMakeLists.txt, llarp/constants/version.cpp.in, llarp/constants/version.hpp, llarp/router/router.cpp, llarp/router_contact.cpp, llarp/router_contact.hpp, llarp/router_version.cpp, llarp/router_version.hpp, test/CMakeLists.txt, test/router/test_llarp_router_version.cpp
serialize router version in rc and set it when we run as service node
=> add router version

llarp/path/pathbuilder.cpp
if we fail to deliver a path build to the first hop mark it as failure.
=> only mark path build success if delivered to first hop

llarp/router/rc_lookup_handler.cpp, llarp/rpc/rpc.cpp, llarp/service/intro_set.cpp
Changing this log statement to LogDebug:
```
Doing explore via public node: cn7uetyozm1ndw336m6sau83hdixf4uar8wzct8hcgkqwqxtgr4y.snode
```
=> s/LogInfo/LogDebug/ @ explore message

llarp/dht/messages/findintro.cpp, llarp/service/hidden_service_address_lookup.cpp
for a find intro message, if relayed try closer router if we don't have the entry requested.
=> try closer router if relayed

llarp/iwp/session.cpp
reduces the number of redundant packets sent between nodes
=> Reduce iwp multiack transmission frequency

llarp/handlers/tun.cpp, llarp/service/context.cpp, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp
using `reachable=false` to disable publishing introsets
=> make publishing introsets optional 

llarp/dht/context.cpp, llarp/dht/context.hpp, llarp/dht/messages/pubintro.cpp, llarp/dht/messages/pubintro.hpp, llarp/dht/publishservicejob.cpp, llarp/dht/publishservicejob.hpp, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp, test/dht/mock_context.hpp
TODO:
1) Ensure this won't create a loop (maybe I shouldn't have ripped out `depth` ...)
2) ~~Related: handle case where `relay == true` and we happen to be one of the closest 4~~
3) Test/Unit test
4) Handle case where our node doesn't have a full Node DB
=> Redundant introset propagation

llarp/dht/context.cpp, llarp/dht/context.hpp, llarp/dht/localserviceaddresslookup.cpp, llarp/dht/messages/findintro.cpp, llarp/dht/messages/findintro.hpp, llarp/dht/messages/pubintro.cpp, llarp/dht/messages/pubintro.hpp, llarp/dht/publishservicejob.cpp, llarp/dht/publishservicejob.hpp, llarp/dht/serviceaddresslookup.cpp, llarp/dht/serviceaddresslookup.hpp, llarp/dht/taglookup.cpp, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp, llarp/service/hidden_service_address_lookup.cpp, test/dht/mock_context.hpp
This builds off of #1111 and cleans up the lookup side of things
=> Redundant introset lookup improvements

llarp/path/path.cpp, llarp/path/pathbuilder.cpp
Someone set us up the `make format`
=> Fix the build 

daemon/lokinetctl.cpp, daemon/main.cpp
...because the world just can't handle the hard ones
=> Remove 'clang-format off' and make format

llarp/dht/context.cpp, llarp/dht/context.hpp, llarp/router/router.cpp
this code is handled by `RCGossiper` and is not needed.
=> remove uneeded code

llarp/config/key_manager.cpp, llarp/nodedb.cpp
=> only try fetching identity key once so we can interrupt lokinet

llarp/nodedb.cpp
add additional case for if we are near the end and all elements are in the exlcude set
=> add additional case 

llarp/exit/session.cpp
respect path builder cooldown.
=> limit path builds on snode sessions

llarp/handlers/tun.cpp
random.snode needs an A record for you to be able to access it. :P
=> add an A Record for random.snode so that it works

contrib/py/admin/lokinetmon
updates lokinetmon to set host header to match what lokinet expects
=> update lokinetmon to work again with dns rebinding protection

.gitlab-ci.yml
this should make gitlab ci poop out windows installers (probably)
=> fix gitlab ci file

.gitlab-ci.yml, Makefile, cmake/unix.cmake
=> make apple builds build for older versions and embrace the bitrot

cmake/win32.cmake
this line removed was causing a compile error
=> fix ci for win32

contrib/macos/lokinet_macos_daemon_script.sh, contrib/macos/lokinet_uninstall.sh
Much touching and sleeping required because macOS is so great.
=> More macos hacks

llarp/config/config.cpp, llarp/config/config.hpp, llarp/context.cpp, llarp/router/router.cpp, llarp/tooling/router_hive.cpp, llarp/tooling/router_hive.hpp, pybind/llarp/config.cpp, test/hive/hive.py
This was sitting in my stash -- there's probably good and bad here
=> Some maybe-fixes for RouterHive post config cleanup

contrib/macos/lokinet_macos_daemon_script.sh
=> Fix DNS "claiming" on Mac when no explicit DNS is set

llarp/CMakeLists.txt, llarp/config/key_manager.cpp
Should fix win32 (which doesn't link to curl).
=> Only link curl if we set up a curl target

.gitattributes, CMakeLists.txt, Makefile, contrib/macos/lokinet_macos_daemon_script.sh, contrib/macos/lokinet_uninstall.sh
There are not many actual changes here, but having the merge history in place helps a lot when merging `dev` into `master` (which will help me auto-build dev debs).
=> Merge master

.drone.jsonnet, cmake/DownloadLibCurl.cmake, contrib/ci/drone-check-static-libs.sh, contrib/ci/drone-debs-upload.sh, contrib/ci/drone-static-upload.sh
Uploads everything to https://builds.lokinet.dev
=> Drone static build and deb uploads

contrib/cross/mingw_core.cmake, daemon/main.cpp, llarp/config/key_manager.cpp, llarp/context.cpp, llarp/crypto/types.cpp, llarp/crypto/types.hpp, llarp/nodedb.cpp, llarp/router/router.cpp, llarp/router_contact.cpp, llarp/router_contact.hpp, llarp/util/bencode.hpp, llarp/util/logging/logger_internal.cpp
aw crap i lost the other half of this where i started doing the refactoring in #1251
=> fix wstring path conversions

llarp/path/transit_hop.cpp
this makes transit hops work again (hopefully)
=> Unfug transit hops

llarp/router/router.cpp
This addresses issues with #1297 by reverting to previous logic with one exception: clients don't write their RC to disk.
=> Better fix for client RC construction

llarp/handlers/tun.cpp, llarp/path/transit_hop.cpp, llarp/router/router.cpp
=> unfug transit hops (again)

include/llarp.hpp, llarp/config/config.cpp, llarp/config/config.hpp, llarp/config/ini.cpp, llarp/config/ini.hpp, llarp/context.cpp, llarp/ev/ev_libuv.cpp, llarp/router/router.cpp, llarp/service/endpoint.cpp, llarp/service/endpoint_state.cpp, llarp/util/logging/logger.cpp, llarp/util/logging/logger.hpp, test/CMakeLists.txt, test/main.cpp, test/regress/2020-06-08-key-backup-bug.cpp
make sure the bug is squashed with a regression test.
=> add regression test for key backup bug

.drone.jsonnet, contrib/ci/drone-run-router-hive.sh, llarp/tooling/router_hive.cpp, llarp/util/logging/logger.hpp, pybind/CMakeLists.txt, pybind/common.hpp, pybind/llarp/config.cpp, pybind/llarp/context.cpp, pybind/llarp/handlers/pyhandler.hpp, pybind/llarp/logger.cpp, pybind/module.cpp, test/hive/hive.py
make pybind compile again.
add pybind and pytest to run in CI so it doesn't bitrot as much.
depends on #1301
=> add pybind to CI

.drone.jsonnet
Drone's initial clone doesn't include tags or submodules; add a step to
fetch both (rather than doing this in the build step).
=> Add tags/submodules as separate step

CMakeLists.txt
=> disable thread safety anonations for freebsd + gtest

llarp/dns/question.cpp, llarp/dns/question.hpp, llarp/handlers/tun.cpp, llarp/service/endpoint.hpp, llarp/service/intro_set.cpp, llarp/service/intro_set.hpp, test/dns/test_llarp_dns_dns.cpp
- detect localhost on SRV lookup and act accordingly
- correctly match SRV records against request
- re-level log print to debug
=> SRV records fixes

llarp/ev/ev_libuv.cpp, llarp/handlers/tun.cpp, llarp/net/ip_range_map.hpp, llarp/net/route.cpp, llarp/router/router.cpp, llarp/router/router.hpp, llarp/rpc/rpc_server.cpp, llarp/service/endpoint.cpp, llarp/service/endpoint_state.cpp, llarp/service/hidden_service_address_lookup.cpp, llarp/service/outbound_context.cpp, llarp/service/protocol.cpp
this makes route poking work on macos
=> macos route poking

CMakeLists.txt
move requirement of pkg config to earlier in build process.
=> move pkgconfig requirement

llarp/service/endpoint.cpp, llarp/service/identity.cpp, llarp/service/identity.hpp, test/CMakeLists.txt, test/service/test_llarp_service_identity.cpp
=> make errors with service keyfile throw

llarp/peerstats/peer_db.cpp, llarp/router/router.cpp
=> fix peer stats excessive logging

llarp/CMakeLists.txt, llarp/net/ip_address.cpp, llarp/net/ip_address.hpp, llarp/net/ip_range_map.hpp, llarp/router/abstractrouter.hpp, llarp/router/route_poker.cpp, llarp/router/route_poker.hpp, llarp/router/router.cpp, llarp/router/router.hpp, llarp/rpc/rpc_server.cpp, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp
if we have no exit enabled disable the route poking.
=> dont poke routes if we have no exit

llarp/router_contact.cpp, llarp/router_contact.hpp, llarp/util/aligned.hpp, test/CMakeLists.txt, test/test_llarp_router_contact.cpp
Implements the new RouterContact format.  This PR does not cause the code to create the new RC format, but it is able to read and write it.
=> New RC format

llarp/config/config.cpp, llarp/config/config.hpp, llarp/config/ini.cpp, llarp/config/ini.hpp, llarp/router/route_poker.cpp, llarp/router_contact.hpp, llarp/service/endpoint.cpp, llarp/service/identity.cpp
serialize auth codes for endpoints in rpc so the gui can see them
=> serialize auth codes in rpc

llarp/iwp/session.cpp, llarp/router/outbound_message_handler.cpp, llarp/service/sendcontext.cpp
=> ammend log levels for common spammy log events

llarp/config/config.cpp, llarp/config/key_manager.cpp, llarp/router/router.cpp, llarp/router_contact.cpp, llarp/rpc/lokid_rpc_client.cpp, readme.md, readme_es.md, test/exit/test_llarp_exit_context.cpp
associated fixes before 0.8.0 retag
=> fixes for 0.8.0 retag

.drone.jsonnet
Should make things faster, especially nlohmann cloning.
=> Drone: Shallow clone submodules

llarp/config/config.cpp
Fixes default config not working.
=> Set default inbound link to best public interface

llarp/handlers/null.hpp, llarp/handlers/tun.cpp, llarp/handlers/tun.hpp, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp, pybind/llarp/handlers/pyhandler.hpp
this may or may not help with tcp throughput.
=> order packets when writing to network interface
