loki-project/loki-network

llarp/ev.hpp, llarp/ev_epoll.hpp, llarp/ev_win32.hpp, llarp/router.cpp, llarp/win32_intrnl.c
Also changed the epoll_wait timeout to 10ms in llarp_epoll_loop::run() to match the other platforms.
***it's finally here***
~~but Bencode is seriously broken on Windows~~
-despair86
=> This completes the Windows NT Server port of the LokiNetwork components.

include/llarp/ip.hpp, include/llarp/logger.hpp, include/llarp/path.hpp, include/llarp/time.hpp, llarp/handlers/tun.cpp, llarp/ip.cpp, llarp/path.cpp
use incremental checksum calculation where we can.
support UDP checksum recalculation.
also fixes some bugs and cleans up bogus code.
=> tun+ip: lots of NAT and checksum (re)calculation improvements

include/llarp.h, include/llarp/handlers/tun.hpp, include/llarp/ip.hpp, include/llarp/net.hpp, include/llarp/service/context.hpp, llarp/context.cpp, llarp/handlers/tun.cpp, llarp/ip.cpp, llarp/service/context.cpp
introduces byte order specific `nuint32_t` and `huint32_t` types and functions to convert these.
modifies part of codebase to use that.
fix bug probably introduced by https://github.com/loki-project/loki-network/commit/cbfc73515e093c9b443b530a972bca5e0f2f7df7 (that was fixed in my earlier PR, fucked up because merge on different base?).
plz review if I didn't do any mistakes with byte ordering.
=> codebase cleanups and some fixes

include/llarp/ip.hpp, llarp/handlers/tun.cpp, llarp/ip.cpp
do not assume that packets come with address zero-ed, older clients don't do that.
they don't modify checksum either, therefore we should be able to get correct checksum if we use deltachksum with old and new addresses.
=> ip: code cleanups and compatibility improvements

include/llarp/net.hpp, llarp/ev_win32.hpp, llarp/link/utp.cpp, llarp/router.cpp
`this->ip4addr` was no longer written to after the switch to `llarp::Addr`, which left it pointing to zeros or a system-specific test pattern (on Windows: `BA AD F0 0D`) which was later written verbatim to the RC file
=> fix router configuration bug

.gitignore, CMakeLists.txt
- Bump to require version 3.7.0
- Change to use `add_compile_options` over manually appending to
`CMAKE_C_FLAGS` or `CMAKE_CXX_FLAGS`.
- Use CMake machinery to set expected C++ standard
- Use CMake machinery to find flag(s) for pthread build
=> Modernise CMake build

include/llarp/service/endpoint.hpp, llarp/service/endpoint.cpp
swap `endpoint.hpp` to modern `using` declarations for types (and remove duplicated type instance), then fix broken build.
=> Fix compile issue in endpoint.cpp

CMakeLists.txt, llarp/config.cpp, llarp/handlers/tun.cpp
Deprecate DNS_PORT (it had a bug and is now configurable via INI anyways)
Improve linux UX: Make 127.3.2.1 the default on linux (so you don't have to fug with systemd) when writing default config
Also tone down the debug a bit on the reverse ip lookup.
=> DNS QoL improvements

include/llarp/service/context.hpp, llarp/router.cpp, llarp/router.hpp, llarp/service/context.cpp
this allows the default network interface options to be specified in the `[network]` section in `lokinet.ini` instead of just via a seperate file via the `[services]` section
=> better config settings for defaults

lokinet-bootstrap
Fixes simple errors in bootstrap script causing it to not work on macOS
=> fix lokinet bootstrap script

CMakeLists.txt, llarp/dht/key.hpp, test/test_llarp_dht_key.cpp
Nice hack of using `std::iota` to simplify the xor test.
=> Add tests for llarp::dht::Key_t

include/tl/optional.hpp, llarp/ev_win32.hpp, llarp/exit/endpoint.cpp, llarp/exit/session.cpp, llarp/logger.hpp, llarp/messages/dht.hpp, llarp/messages/discard.hpp, llarp/messages/exit.hpp, llarp/messages/path_confirm.hpp, llarp/messages/path_latency.hpp, llarp/messages/path_transfer.hpp, llarp/messages/transfer_traffic.hpp, llarp/path.cpp, llarp/pathbuilder.cpp, llarp/pathbuilder.hpp, llarp/resource.h, llarp/router.cpp, llarp/router.hpp, llarp/routing/handler.hpp, llarp/routing/message.hpp, llarp/routing/message_parser.hpp, llarp/win32_upoll.c, llarp/win32_upoll.h
windows port should be working now
still need to do some testing on my other devices
features such as setting lokinet as default route will be the next pull
but hidden service and service node access is working
```
i'd think the event loop queues are a thing because
of the way unix handles non-blocking i/o
[got to wait for files/sockets to become writable, 
so once you get the data off the network card, 
you still have to wait for the device to become ready, 
so you put the data on the queue until then]
but on windows, async i/o to sockets, files, or devices is easy
no need to wait for anything
```
=> let's get this show on the road

.github/CONTRIBUTING.md, CONTRIBUTING.md
1. The .github copy is what currently appears when creating pull requests
2. The .github copy is older and sparser
3. I'm pretty sure the presence of the .github copy is what prevents the root copy from being respected <https://blog.github.com/2016-02-17-issue-and-pull-request-templates/>
All that being said, I don't have an easy way to test that this does what I expect before it is merged.  And is the `lint` pass still requested?
=> Consolidate multiple CONTRIBUTING files

.gitignore, CMakeLists.txt, Makefile, llarp/ev/ev_kqueue.hpp, readme.md
See the initial data with https://michael-loki.github.io/loki-network/
To generate with clang tools:
1. `cmake -DWITH_COVERAGE=ON -DUSING_CLANG=ON`
2. `<make>`
3. `./testAll`
4. `llvm-profdata merge default.profraw -output profdata`
5. `llvm-cov show -format=html -output-dir=<outdir> -instr-profile profdata ./testAll $(find ../llarp -type f)`
=> Add flag to generate coverage data

daemon/main.cpp, llarp/handlers/tun.cpp, llarp/router/router.cpp
We usually fail because there's already a DNS server there.
When doing advanced configuration, it's very easy to bind two DNS to the same port but it doesn't really matter, we just need one working lokinet DNS servers, the 2nd really doesn't matter (unless you're doing static HS mappings)
My future hope is to warn if it's a lokinet DNS server otherwise fail/exit
UPDATE:
- Delaying autodetection for better results
- Address #251 (if I say 404.ini don't make it without -g or -c)
- Improve UX: 
- resolves ~/symlinks to final path on disk
- output CWD/PWD making support easier
=> downgrade DNS server failure to a warning, autodetection delay, and don't create config if explicitly and no options

llarp/util/buffer.cpp
the deference of buff->cur when it was already at the end would trigger the buffer overrun
fixes issue #263
=> fix buffer overrun

llarp/dns/message.cpp, llarp/handlers/tun.cpp
applications MUST use CNAME as random.snode returns a random entry every time.
=> disable CNAME RR for random.snode A record lookups

llarp/context.cpp, llarp/dht/context.cpp, llarp/dht/context.hpp, llarp/dht/explorenetworkjob.cpp, llarp/dht/localrouterlookup.cpp, llarp/dht/localserviceaddresslookup.cpp, llarp/dht/localtaglookup.cpp, llarp/dht/messages/findrouter.cpp, llarp/dht/messages/gotintro.cpp, llarp/dht/messages/gotrouter.cpp, llarp/dht/messages/pubintro.cpp, llarp/exit/session.cpp, llarp/handlers/exit.cpp, llarp/link/utp.cpp, llarp/messages/dht_immediate.cpp, llarp/messages/link_intro.cpp, llarp/path/path.cpp, llarp/path/path.hpp, llarp/path/pathbuilder.cpp, llarp/path/transit_hop.cpp, llarp/router/router.cpp, llarp/router/router.hpp, llarp/rpc/rpc.cpp, llarp/service/context.cpp, llarp/service/endpoint.cpp, llarp/service/lookup.cpp, test/dht/mock_context.hpp
This doesn't convert it everywhere, but in "most" places. Further iterations on this would be:
- Move `AbstractRouter` into its own header, which would hopefully break some of the dependency cycles and improve compile times
- Replace the rest of the usage of `Router` in the majority of places with the interface.
=> Convert llarp::Router into an abstract base class

CMakeLists.txt, llarp/net/exit_info.cpp, llarp/net/exit_info.hpp, llarp/util/bits.hpp, test/util/test_llarp_util_bits.cpp
Expand to handle any container (not just C-style arrays).
clang manages to vectorise this which is cool - https://godbolt.org/z/lMD1eD for vector, https://godbolt.org/z/7ySPBe for array. for smaller array the assembler looks ~equivalent.
=> Refactor and add tests for bits.hpp

CMakeLists.txt
If ccache is in the path, use it to accelerate builds.
see https://cmake.org/cmake/help/latest/prop_gbl/RULE_LAUNCH_COMPILE.html
=> Add support for building with ccache

CMakeLists.txt
This is experimental, and has a bunch of false positives.
=> Remove negative thread safety warning flag

llarp/profiling.cpp, llarp/profiling.hpp
`Profiling::Load` calls `BDecodeReadFile` under a lock, which ends up calling `DecodeKey`, which then tries to lock the mutex again.
=> Fix deadlock in profiling

CMakeLists.txt, daemon/main.cpp, llarp/CMakeLists.txt, llarp/router/router.cpp, llarp/util/metrics.cpp, llarp/util/metrics.hpp, llarp/util/metrics_core.cpp, llarp/util/metrics_core.hpp, llarp/util/metrics_publishers.cpp, llarp/util/metrics_publishers.hpp, llarp/util/metrics_types.cpp, llarp/util/metrics_types.hpp, llarp/util/object.cpp, llarp/util/object.hpp, llarp/util/scheduler.cpp, llarp/util/scheduler.hpp, llarp/util/stopwatch.cpp, llarp/util/stopwatch.hpp, llarp/util/timerqueue.cpp, llarp/util/timerqueue.hpp, test/CMakeLists.txt, test/test_util.hpp, test/util/test_llarp_util_metrics_core.cpp, test/util/test_llarp_util_metrics_publisher.cpp, test/util/test_llarp_util_metrics_types.cpp, test/util/test_llarp_util_object.cpp, test/util/test_llarp_util_timerqueue.cpp, test/util/test_llarp_utils_scheduler.cpp
3 commits (developed in sync, just grouped some what logically).
1. Adds some useful utilities 
2. Adds metric collection mechanisms 
3. Sample integration with lokinet:
- Instantiates a metric manager in main
- Adds a publisher scheduler in main
- Creates a streaming publisher to `stdout` 
- Adds some initial collection work to `router/router.cpp`
Work to do (but this should still be mergeable in this state):
- empty metric GC (once a metric is posted once, we always keep track of it)
- json dumper / rotator so we don't fill everyone's disks up
- a remote metrics collector for debugging for lokinet devs (pushing to metric tank or something)
- adding them in more places in the code (the current integration is just sample)
=> Metrics Collection System

libutp/utp_packedsockaddr.cpp, llarp/messages/relay_commit.hpp, llarp/service/endpoint.hpp
`sa` is not an actual object. here `len` is 16, and `sockaddr_storage` is 100+ bytes.
This fixes *an* issue with the address sanitizer
=> Fixup one ASAN warning

CMakeLists.txt, llarp/iwp/linklayer.cpp, llarp/iwp/linklayer.hpp, llarp/link/server.cpp, llarp/link/server.hpp, llarp/link/session.hpp, llarp/utp/linklayer.cpp, llarp/utp/linklayer.hpp, llarp/utp/session.cpp, llarp/utp/session.hpp, test/test_libabyss.cpp, test/util/test_llarp_util_thread_pool.cpp
fixes 2 of the 3 outstanding asan issues.
notes:
- ownership of the `ILinkSession` is shared between AuthedLinks and PendingLinks
- hoist common methods up to the interface to avoid use of bare `new`
=> Fix more address sanitiser issues

llarp/ev/pipe.cpp
only freebsd has `O_DIRECT` (and the only other platform that _does_, is obsolete: SGI IRIX)
=> fix UNIX ports

llarp/metrics/metrictank_publisher.cpp
some of the more useful functions graduated to the main libc
=> when SunOS 4.x/Sun386i compatibilty was yanked,

llarp/dht/bucket.hpp, llarp/dht/context.cpp, llarp/dht/context.hpp, llarp/dht/node.hpp, llarp/dht/tx.hpp, llarp/dht/txholder.hpp, llarp/dht/txowner.hpp, llarp/exit/context.hpp, llarp/exit/endpoint.hpp, llarp/exit/session.hpp, llarp/handlers/exit.hpp, llarp/handlers/tun.hpp, llarp/link/server.hpp, llarp/link/session.hpp, llarp/path/path.hpp, llarp/path/pathbuilder.hpp, llarp/router/abstractrouter.cpp, llarp/router/abstractrouter.hpp, llarp/router_contact.hpp, llarp/router_id.hpp, llarp/service/Intro.hpp, llarp/service/IntroSet.hpp, llarp/service/context.hpp, llarp/service/endpoint.hpp, llarp/service/lookup.hpp, llarp/service/tag.hpp, llarp/util/status.hpp
This makes a whole lot of otherwise simple classes virtual with no real benefit. "Convention" around the `ExtractStatus` method should be sufficient.
If required, we could make a trait for this instead, but I don't think it's needed.
=> Remove IStateful virtual inheritance

llarp/CMakeLists.txt, llarp/handlers/tun.cpp, llarp/service/async_key_exchange.cpp, llarp/service/async_key_exchange.hpp, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp, llarp/service/hidden_service_address_lookup.cpp, llarp/service/hidden_service_address_lookup.hpp, llarp/service/lookup.cpp, llarp/service/outbound_context.cpp, llarp/service/outbound_context.hpp, llarp/service/pendingbuffer.cpp, llarp/service/pendingbuffer.hpp, llarp/service/sendcontext.cpp, llarp/service/sendcontext.hpp, llarp/service/session.cpp, llarp/service/session.hpp, llarp/service/tag_lookup_job.cpp, llarp/service/tag_lookup_job.hpp
This is mostly a mechanical refactoring, splitting private classes out into their own files. 
end result:
| file | lines before | lines after | %age |
| --- | ------------ | --------- | ---------------- |
| endpoint.cpp | 2050 | 1215 |  60% |
| endpoint.hpp | 680 | 422 | 62% |
=> Refactor service::Endpoint into multiple chunks

llarp/CMakeLists.txt, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp, llarp/service/endpoint_util.cpp, llarp/service/endpoint_util.hpp
Does two things:
- simplifies logic in the main class
- makes these things more testable/composable
=> Refactor well named functionality in service::Endpoint into new struct

llarp/router/router.cpp
i dont know why i didn't see this before but this was not the correct behavior `._.`
=> correct function behavior

llarp/service/outbound_context.cpp
when we get told by the endpoint of a path that the path we are sending to is gone we need to switch intros immediately.
=> swap intros on message rejection

llarp/service/endpoint.cpp, vendor/libtuntap-master/tuntap-unix.c
macos tun was borked because it requires packet info in the the read and write ops on the tun.
this compiles but is kinda shit as it does not have const correctness.
=> Fix mac os tun pi

llarp/hook/shell.cpp, llarp/router/router.cpp, llarp/util/thread_pool.cpp, llarp/util/thread_pool.hpp, llarp/util/threading.cpp, llarp/util/threading.hpp, llarp/util/threadpool.h, test/util/test_llarp_util_thread_pool.cpp
looks like:
```
(lldb) thread list
Process 17698 stopped
* thread #1: tid = 0x6d3a6, 0x00007fff6966c78e libsystem_kernel.dylib`kevent + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
thread #2: tid = 0x6d45f, 0x00007fff6966986a libsystem_kernel.dylib`__psynch_cvwait + 10
thread #3: tid = 0x6d462, 0x00007fff6966986a libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'llarp-worker'
thread #4: tid = 0x6d463, 0x00007fff6966986a libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'llarp-worker'
thread #5: tid = 0x6d464, 0x00007fff6966986a libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'diskworker'
```
makes debugging multithreaded issues/cores **soooooooooooo** much nicer.
=> Add function to set threadname, and use from threadpool impl

include/llarp.hpp, llarp/CMakeLists.txt, llarp/handlers/tun.cpp, llarp/net/net_int.hpp, llarp/path/pathbuilder.hpp, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp, llarp/service/endpoint_state.cpp, llarp/service/endpoint_state.hpp, llarp/service/endpoint_types.hpp, llarp/service/endpoint_util.cpp, llarp/service/endpoint_util.hpp, llarp/service/handler.hpp, llarp/service/outbound_context.cpp, llarp/service/router_lookup_job.cpp, llarp/service/router_lookup_job.hpp, vendor/libtuntap-master/tuntap-unix.c
added bonus: `service::Endpoint` should now be default-moveable which is nice.
=> Refactor endpoint state management to a new class

llarp/service/sendcontext.cpp, llarp/utp/linklayer.cpp, llarp/utp/session.cpp, llarp/utp/session.hpp
this helps prevent some unneeded timeouts on utp layer.
=> only call utp_issue_deferred_acks before timing out sessions

lokinet-bootstrap
- takes an optional second argument to control where to download
- print usage info if called with >2 arguments or an argument starting with `-`
- Add `set -e` so if unchecked things fail (e.g. the mkdir) the script fails.
I have no idea how to update the `lokinet-bootstrap.exe` file.
=> lokinet-bootstrap improvements

docs/proto_v0.txt, llarp/CMakeLists.txt, llarp/crypto/encrypted_frame.cpp, llarp/crypto/encrypted_frame.hpp, llarp/messages/link_message_parser.cpp, llarp/messages/relay_commit.cpp, llarp/messages/relay_status.cpp, llarp/messages/relay_status.hpp, llarp/path/ihophandler.hpp, llarp/path/path.cpp, llarp/path/path.hpp, llarp/path/path_context.cpp, llarp/path/path_context.hpp, llarp/path/pathset.hpp, llarp/path/transit_hop.cpp, llarp/path/transit_hop.hpp, llarp/router/abstractrouter.hpp, llarp/router/router.cpp, llarp/router/router.hpp, llarp/util/threadpool.cpp, llarp/util/threadpool.h
Success case:
- the path endpoint creates and sends a LR_StatusMessage upon
successful path creation
Failure case:
- an intermediate hop creates and sends a LR_StatusMessage upon
failure to forward the path to the next hop for any reason
Both cases:
- transit hops receive LR_StatusMessages and add a frame
to them reflecting their "status" with respect to that path
- the path creator receives LR_StatusMessages and decrypts/parses
the LR_StatusRecord frames from the path hops.  If all is good,
the Path does as it would when receiving a PathConfirmMessage.
If not, the Path marks the new path as failed.
LR_StatusMessage is now used/sent in place of PathConfirmMessage
=> Adds Link-Relay Status Messages

llarp/utp/linklayer.cpp, llarp/utp/session.cpp
this helps prevents clients from being flooded off the network
=> dont close backlogged client connections

llarp/router/outbound_session_maker.cpp
Currently if there isn't an outbound link, `GotRouterContact` will call `FinalizeRequest` with the mutex still held, and deadlock.
=> Fix a deadlock when link fails to establish

docker/compose/compose-base.Dockerfile, llarp/net/address_info.cpp, llarp/net/address_info.hpp, llarp/router_contact.cpp
```json
./lokinet-rcutil --dump ~/.lokinet/bootstrap.signed --json | jq . 
{
"/Users/foo/.lokinet/bootstrap.signed": {
"addresses": [
{
"dialect": "utp",
"in6_addr": "::ffff:51.79.57.235",
"port": 1090,
"pubkey": "632d43917c5f5e45a079690d906f825b20c3931d32b1c26115d529a48d710a11",
"rank": 1
}
],
"exit": false,
"identity": "e883ba38963ada84dbf88a3223727d123a75b07b20cb4fd7ce8ce3983a76e625",
"lastUpdated": 1565820374503,
"publicRouter": true
}
}
```
=> Dump more info from router contact

llarp/ev/ev.cpp, llarp/router/router.cpp, osx-setup/distribution.xml, osx-setup/resources/conclusion.html, osx-setup/resources/welcome.html, osx-setup/scripts/postinstall
for @neuroscr 
also:
- don't warn when netid == default netid (some scripts set netid explicitly)
- windows error feedback for @KeeJef (instead of showing random network setup errors, tells the user to check their config file, just like all the other platforms were already doing)
=> macOS installer bump / Other windows fixes

llarp/iwp/linklayer.cpp, llarp/link/server.hpp
i found no lock contention on the link layer mutexes with tracy so we should revert these into Null{Lock,Mutex} like they were before.
=> disable link layer locking

CMakeLists.txt, Makefile, cmake/static_link.cmake, cmake/static_link_runtime.cmake, cmake/unix.cmake
fixes #823 
```
$ otool -L lokinet
lokinet:
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.6.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```
=> Statically link releases

llarp/service/endpoint.cpp, llarp/service/endpoint.hpp, llarp/service/endpoint_util.cpp, llarp/service/handler.hpp, llarp/service/outbound_context.cpp, llarp/service/sendcontext.cpp, llarp/service/session.cpp
=> try fixing handover

llarp/path/pathbuilder.hpp, llarp/service/endpoint_util.cpp, llarp/service/outbound_context.cpp, llarp/service/outbound_context.hpp, llarp/service/sendcontext.cpp
this is the revision that officially renders the handover drop bug gone.
=> final touches for handover drop bug

llarp/rpc/rpc.cpp
```
$ curl -s -X POST -H 'content-type: application/json' --data '{"method": "llarp.version", "params": {}, "id": "foo"}' localhost:1190/jsonrpc | jq .
{
"id": "foo",
"jsonrpc": "2.0",
"result": {
"version": "lokinet-0.5.2-8f46a62a"
}
}
```
=> Support version over jsonrpc

daemon/main.cpp, include/llarp.h, include/llarp.hpp, llarp/context.cpp, llarp/router/abstractrouter.hpp, llarp/router/router.cpp, llarp/router/router.hpp, llarp/rpc/rpc.cpp
fixes #853
what's currently broken:
- ctrl-c to kill if you've not sent the start command(??)
=> Introduce --background to only start JSON RPC

llarp/router/router.cpp
This adds the number of nodes in the `nodedb` to the `llarp.admin.dumpstate` endpoint. 
It might be better / more consistent to add an `ExtractStatus()` method to `nodedb`, though there doesn't seem to be much else in `nodedb` we might want to know.
Also note that `num_loaded()` is going to acquire the `nodedb`'s `access mutex`; would this be problematic?
=> Add numNodesKnown to llarp.admin.dumpstate RPC endpoint

CMakeLists.txt, llarp/net/net.cpp
- xenial's cmake version (3.5.1) builds everything fine and test suite
passes, so lower the minimum to that.
- add a hack for xenial's kernel header & glibc version breaking if both
net/if.h and linux/if.h get included.  The only thing we actually need
from net/if.h that linux/if.h doesn't have is `if_nametoindex`, so
just hack that definition in for xenial's specific glibc/kernel header
versions.
This travis-ci build doesn't hit either of these issues because it isn't fully xenial - it's xenial plus updated headers and cmake versions because WTF travis.
=> Fix build on xenial

CMakeLists.txt, cmake/MacroEnsureOutOfSourceBuild.cmake
Prevent user from running `cmake` in root project directory as this causes a ridiculous mess
=> Prevent in-source-builds with cmake macro

llarp/iwp/message_buffer.cpp, llarp/iwp/session.cpp, llarp/messages/relay.cpp, llarp/path/path.cpp
bigger link messages like those for path builds are not delivered fast enough because we wait to flush the encrypt packet buffer after handling decrypted packets until we get more packets from the network.
this should fix that
=> make path builds work

llarp/ev/ev.hpp, llarp/messages/link_message.hpp, llarp/messages/relay.hpp, llarp/messages/relay_commit.cpp, llarp/path/path.cpp, llarp/path/path_context.cpp, llarp/path/path_types.hpp, llarp/path/pathbuilder.cpp, llarp/path/pathset.cpp, llarp/path/pathset.hpp, llarp/router/i_outbound_message_handler.hpp, llarp/router/outbound_message_handler.cpp, llarp/router/outbound_message_handler.hpp, llarp/router/router.cpp, llarp/service/info.cpp, llarp/service/info.hpp
TODO: make sure that paths we create (as a client) are removed from the per-path queues.
TODO: research / trial & error on how best to manage messages sent per tick
=> Add per-path queues, prioritize control messages over traffic

llarp/util/thread/threading.hpp
Leaving some additional breadcrumbs for anyone who stumbles across NullMutex might help it achieve its purpose.
=> Null mutex clarity (via comments / log statement)

llarp/iwp/linklayer.cpp, llarp/iwp/session.cpp, llarp/iwp/session.hpp, llarp/link/session.hpp
This prevents any new inbound session from hanging around if it's already broken upon receiving the first packet. Strictly speaking, it doesn't fix the underlying problem (which is that broken sessions aren't being cleaned up properly), but it does prevent the most common use cases, and it's generally a good performance optimization as well.
=> Fix #911: Drop new inbound IWP sessions when the first packet can't be handled

crypto/libntrup/src/ntru.cpp
The feature flags come via __cpuid_count instead of __cpuid
Also removes a couple unneeded headers.
=> Fix runtime AVX2 detection

daemon/main.cpp, llarp/util/bencode.hpp
resolvePath was leaking memory (the returned char * from realpath was
never freed), but upon closer inspection resolvePath doesn't seem right:
shell/glob/~ expansion is the job of the shell, not the argument (but
worse, if you pass it something like '~' (quoted) it would expand, which
is wrong.
Also de-duplicate some code.
(Strongly recommend to view this diff hiding whitespace changes).
=> Remove shell globbing of path

llarp/ev/ev.h
When there's nothing waiting we wait this long unconditionally, but that
can add a lot of latency across a path.
There are likely better ways to handle this via libuv's run handlers,
but this addresses the latency until we figure that out.
=> Lower the ev tick interval to 10ms

Makefile, llarp/ev/ev_libuv.cpp, llarp/ev/ev_libuv.hpp, llarp/handlers/tun.cpp, llarp/handlers/tun.hpp, llarp/iwp/linklayer.cpp, llarp/iwp/linklayer.hpp, llarp/link/server.cpp, llarp/net/ip.cpp, llarp/path/transit_hop.cpp, llarp/path/transit_hop.hpp, llarp/router/router.cpp, llarp/router/router.hpp, llarp/service/async_key_exchange.cpp, llarp/service/async_key_exchange.hpp, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp, llarp/service/handler.hpp, llarp/service/outbound_context.cpp, llarp/service/protocol.cpp, llarp/service/sendcontext.cpp, llarp/util/thread/logic.cpp, llarp/util/thread/logic.hpp, llarp/util/thread/timer.cpp
Cherry picked and cleaned up from all the various fixes we applied over the last few days on a mess of branches.
=> Logic thread fixes

llarp/config/key_manager.cpp, llarp/config/key_manager.hpp, llarp/dht/messages/findintro.cpp, llarp/dht/messages/gotrouter.cpp, llarp/ev/ev_win32.cpp, llarp/iwp/iwp.cpp, llarp/iwp/iwp.hpp, llarp/iwp/linklayer.cpp, llarp/iwp/linklayer.hpp, llarp/link/factory.hpp, llarp/link/server.cpp, llarp/link/server.hpp, llarp/messages/relay.cpp, llarp/messages/relay_commit.cpp, llarp/messages/relay_status.cpp, llarp/router/abstractrouter.hpp, llarp/router/router.cpp, llarp/router/router.hpp, llarp/service/endpoint.cpp, llarp/service/identity.cpp, llarp/service/identity.hpp, llarp/service/protocol.cpp, llarp/util/bencode.cpp, llarp/util/bencode.h, llarp/util/bencode.hpp, test/link/test_llarp_link.cpp, test/service/test_llarp_service_identity.cpp
Cleaning up stuff that got left behind in the push to get 0.6-rc1 ready.
TODO:
- ~~Reinstate link unit tests~~ (eb5184e)
- ~~Support SNApp keys~~ (Not going to do; see #948)
- ~~Backup SNApp keys~~ (2c6226f)
- ~~Fix client key regen on startup~~ (this didn't break after all)
- Fix ephemeral link keys (doesn't appear to have been working for a while)
- More unit tests
- ~~Make format~~ (66a058a)
- ~~Remove getters/setters~~ (11410a2)
=> Key manager cleanup (post 0.6-rc1)

llarp/router/i_outbound_session_maker.hpp, llarp/router/outbound_session_maker.cpp, llarp/router/outbound_session_maker.hpp, llarp/router/router.cpp
Fixed a compiler warning about an unused argument, plus the argument
legitimately appears unused/obsolete now.
=> Remove unused argument

llarp/util/aligned.hpp
`extern`  is a bit ugly, but this was already used in `AlignedBuffer`...
Interesting note: I actually got better performance with something like this in `IsZero()`:
```cpp
if (sz % sizeof(uint64_t) == 0) {
// cast data() as uint64_t* and iterate over array as such
} else {
// delegate to sodium_is_zero
}
```
=> Optimize AlignedBuffer:::IsZero()

llarp/util/aligned.hpp
Simplifies alignment implementation and changes alignment from uint64_t to std::max_align_t.  See commit comments for more details.
=> Aligned buffer simplify

include/tuntap.h
Loading both net/if.h and linux/if.h on xenial breaks compilation
because xenial's kernel/glibc headers are broken AF.
We don't actually need anything from net/if.h here, so just include linux/if.h instead.
=> Don't include net/if.h to help xenial

vendor/nlohmann/CMakeLists.txt
per https://github.com/loki-project/loki-network/blob/ubuntu/xenial/debian/patches/0004-Reduce-required-cmake-version.patch
=> Xenial compatibility

llarp/util/aligned.hpp, test/util/test_llarp_util_aligned.cpp
Use `memcpy` to extract hash value
Using the straight `reinterpret_cast` runs into type aliasing issues, which manifest on armhf and sometimes on amd64 for the larger 1024 test (which we removed but get readded here).  C++20 adds `std::bit_cast` to deal with exactly this, but `std::memcpy` is the pre-C++20 way to do it reliably.
=> AlignedBuffer<N>::Hash fix

CMakeLists.txt
this still allows Debian pkg builds to use their own target specfic flags
=> IX86 builds should only require SSE3 by default

llarp/iwp/session.cpp, llarp/iwp/session.hpp
Changes to report IWP session stats in the `dumpstate` API call. Used by the GUI to display instantaneous bandwidth usage.
=> add bw stats to iwp sessions

CMakeLists.txt, crypto/CMakeLists.txt
Currently we do runtime AVX2 detection, but it's a bit broken: it only compiles to anything more than stubs if the whole project is compiled with AVX2 support.
This changes it to always attempt to compile the AVX2 ntru code with `-mavx2 -mfma` even when the rest of the code doesn't have AVX2 features enabled so that the run-time detection can let us ship a non-AVX2 binary with the ntru AVX2 optimizations behind the run-time CPU feature detection.
This PR also cleans up the way we set the CPU compiler flags because it was a bit convoluted.
=> Enable AVX2 compilation whenever possible

crypto/libntrup/src/ntru.cpp
The optional runtime detection code also shouldn't rely on being compiled in avx2 mode.
=> Fix avx2 cpu detection on amd64 (again)

llarp/service/outbound_context.cpp
using shared_from_this prevents an infrequent segfault.
=> prevent segfault

llarp/nodedb.cpp, llarp/nodedb.hpp
Pruning a dead code path in nodedb and updating documentation accordingly
=> Remove dead code in llarp_nodedb::Insert()

llarp/router/rc_lookup_handler.cpp, llarp/router/rc_lookup_handler.hpp
Partially addresses #1047 by limiting lookup frequency of any router to 10 minutes.
=> Lookup routers at maximum frequency of 10 minutes

llarp/router/outbound_message_handler.cpp, llarp/router/outbound_message_handler.hpp, llarp/router/router.cpp
Adds stats about the outbound message queue, particularly designed to help understand where we are hitting self-imposed limits.
@tewinget and @majestrate , please review with consideration of threading safety.
=> Include outbound message queue stats in dumpState API response

llarp/router/outbound_message_handler.cpp
when we want to remove lots of paths flush queue when full then add to queue
=> don't deadlock on path queue removal if full

llarp/handlers/tun.cpp, llarp/handlers/tun.hpp
if `EnsurePathToXXXX` returns false it doesn't call the hook which causes a leak.
=> use std::shared_ptr not a bare pointer to prevent memleak

llarp/iwp/session.cpp, llarp/iwp/session.hpp
IWP session JSON now looks like:
```json
{
"created": 1581100813495,
"inbound": false,
"remoteAddr": "51.15.58.238:1092",
"remoteRC": {
"addresses": [
{
"dialect": "iwp",
"in6_addr": "::ffff:51.15.58.238",
"port": 1092,
"pubkey": "6323893e9aef463ddcef056b2b1aff310bcfb8db3b90176ce25f76bed090144c",
"rank": 2
}
],
"exit": false,
"identity": "4b637c243a38373e6e85a6cd7cf491fb6583da18b991eb51f25acc9dd5d0b74c",
"lastUpdated": 1581098115111,
"publicRouter": true
},
"replayFilter": 9,
"rxMsgQueueSize": 0,
"rxPktsRcvd": 841,
"rxRateCurrent": 9127,
"state": "Ready",
"txMsgQueueSize": 0,
"txPktsAcked": 214,
"txPktsDropped": 0,
"txPktsInFlight": 0,
"txRateCurrent": 5694,
"uptime": 53293
},
```
=> Add IWP session stats to JSON API

llarp/service/endpoint.hpp
We want to have some redundancy, but having 8 active at once seems
extreme; reduce to 4.
=> Reduce introset publishing interal to 2.5min instead of 1.25min

llarp/service/endpoint.cpp, llarp/service/endpoint.hpp, llarp/service/endpoint_state.hpp, llarp/service/endpoint_types.hpp, llarp/service/handler.hpp, llarp/service/outbound_context.cpp
outbound context does not override `pathset::HandleGotIntroMessage` who's default behavior is to drop messages when not overrided. thus we should use the parent endpoint's paths for lookups as it will properly handle replies.
=> Use endpoint path for outbound context introset update

.travis.yml
It doesn't seem like we need this for the mac build.
=> Remove llvm from travis-ci homebrew packages

libabyss/src/http.cpp, llarp/config/config.cpp, llarp/config/ini.cpp, llarp/handlers/tun.cpp, llarp/util/string_view.hpp, test/config/test_llarp_config_ini.cpp, test/util/test_llarp_util_str.cpp
string_view was implicitly convertible to std::string, but
std::string_view is only explicitly convertible.  This makes the
`operator std::string` explicit to be more compatible, and re-adds a
bunch of explicit string casts to the code where needed.
(This also fixes the build if changing the standard to c++17)
=> Fix string_view C++17 compatibility

llarp/constants/path.hpp, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp
Notice what a PITA it is to deal with `std::chrono` and `llarp_time_t` at the same time...
=> Spread snapp path builds evenly

CMakeLists.txt
WITH_SYSTEMD=ON or =OFF works to explicitly enable/disable, but if
omitted the default is now ON if found and OFF if not found.
=> Default libsystemd support to enabled if found

CMakeLists.txt
Prevent `make install` from installing headers/cmake stuff.
=> Add EXCLUDE_FROM_ALL to subprojects

llarp/router/router.cpp
So we get `v0.7.0` instead of `lokinet-0.7.0-abcdef12`; the latter is
useful for devs, but not so much for random operators (and you can
always go get the full version from the binary).
=> Shorten version and prefix with v

.gitattributes, cmake/Version.cmake
the 0.6.4 source tarballs don't build because they have no `.git/index` this makes it so that future tarballs build.
=> allow building from source tarballs

libabyss/include/abyss/server.hpp, libabyss/src/client.cpp, libabyss/src/server.cpp, llarp/rpc/rpc.cpp, test/test_libabyss.cpp
also patches possible dns rebinding vuln. moving to lokimq makes this irrelevant.
=> add llarp.admin.die rpc call to gracefully kill router

.gitattributes
These are part of the source code (in the documentation, and used in the
Windows build) so we really should still be including them.  (We can aim
at eliminating them, but should eliminate them from git, not just from
exported source).
=> Don't ignore .exe, .png, .gif

libabyss/src/server.cpp
connections were not being marked as safe for delete.
=> try fixing leak in libabyss

llarp/dns/message.cpp, llarp/handlers/tun.cpp, llarp/handlers/tun.hpp, llarp/service/endpoint.cpp
also fixes some documentation in `service::Endpoint`
=> strip rr from dns reply for .snode and .loki

llarp/dns/message.cpp, llarp/dns/message.hpp, llarp/handlers/tun.cpp
The logic here wasn't quite right and was returning an A record in response to an AAAA lookup.  DNS resolvers didn't accept that, so `ping` would delay 5 seconds (waiting for the AAAA lookup to return something valid) before giving up and trying an A lookup.
This returns nothing, which is better, but not quite enough: this gives empty responses, which produces warnings in host/dig.
=> Fix IPv6 lookups to return empty response

llarp/router/router.cpp
this also prunes client nodedbs so we don't have rcs from old 0.6.x net that are invalid.
=> better nodedb pruning logic

llarp/nodedb.cpp, llarp/nodedb.hpp
before we were only using routers who we are directly connected to or recently looked up the RC for. now it's uniform random, this should help with spreading out traffic and anonymity related attributes.
=> fully randomize hop selection

llarp/service/intro_set.cpp
this allows us to put more things into introset in the future without breaking compat
=> discard unknown fields in introset for future use

llarp/ev/ev_libuv.cpp
llarp_tcp_acceptor ticker wasn't being called so connections where not
being cleaned up
=> fix memleak in jsonrpc

llarp/handlers/tun.cpp
when we have an inbound session and we do a forward dns lookup we should not look up the descriptor on the network as we already have a session with them.
=> dont request descriptors for inbound sessions

CMakeLists.txt
Just let the pkg_check fail when libsystemd isn't install; it shouldn't
hurt anything.
=> No LINUX variable in cmake

llarp/config/config.cpp, llarp/config/config.hpp, llarp/config/definition.cpp, llarp/config/definition.hpp, llarp/config/key_manager.cpp, llarp/router/router.cpp, test/config/test_llarp_config_definition.cpp
Fixes an issue where `[bind]` section wasn't accepting arbitrary interface names
=> Config fixes 2020 04 29

cmake/GenVersion.cmake
* rev-parse --short without any argument defaults to 8 chars
* truncation is absolutely moot here
* rev-list --abbrev-commit also uses 8 chars by default
because of length mismatch (COMMIT - 9 chars, TAGGEDCOMMIT - 8 chars) it always was mismatching them even when it should've been detecting that it's at release tag.
cut out explicit lengths and leave everything to use defaults, because they work (they both rely on the same core.abbrev setting so no length mismatch should happen).
=> fix GenVersion.cmake

llarp/nodedb.cpp, llarp/profiling.cpp, llarp/router/outbound_session_maker.cpp, llarp/router/router.cpp, llarp/util/meta/traits.hpp, llarp/util/str.hpp, llarp/util/thread/barrier.hpp, llarp/util/thread/thread_pool.cpp, llarp/util/thread/threading.hpp
- class template argument deduction lets us write `std::unique_lock
foo{mutex}` instead of `std::unique_lock<mutex_type> foo{mutex}` which
makes the `unique_lock` and `shared_lock` functions unnecessary.
- Replace GNU-specific warn_unused_result attribute with C++17-standard
[[nodiscard]]
- Remove pre-C++17 workaround code for fold expressions, void_t
=> C++17 niceties

llarp/dht/taglookup.cpp, llarp/iwp/session.cpp, llarp/messages/link_intro.cpp, llarp/router/rc_lookup_handler.cpp, llarp/router_contact.cpp, llarp/util/aligned.hpp
Miss Match was not happy that her name was being used in the code, so I changed it to mismatch.
(i.e. fix speeling mistack: missmatch -> mismatch)
Also annotate the netid mismatch message to indicate which of the mismatched values is ours or theirs.
=> Miss Match & ours/theirs

llarp/config/config.cpp, llarp/service/context.cpp, llarp/service/endpoint.cpp
this made it so that snapps always use ephemeral keys.
this fixes this.
=> keyfile was being initialized before being set by configure call.

llarp/config/config.cpp, llarp/service/context.cpp
IpAddresses in dns section config were not defaulting to port 53 when no port was provided.
Fixes #1264
=> default to port 53 in dns section entries

.drone.jsonnet
GCC 10 stable (10.1.0) released earlier this month and is now in Debian sid (though probably won't be the default for a while), so add a build using it.
=> Add gcc-10 build

llarp/config/config.hpp, llarp/config/key_manager.hpp, test/crypto/test_llarp_key_manager.cpp
These tests were perhaps failing because of uninitialized values. If this fixes the unit tests, we probably should do one of:
* Ensure that Config cant' be used when it hasn't been initialized, or
* Provide proper values at construction time (this is problematic because it will conflict with other default values provided in InitializeConfig(), etc.)
=> Fix various unit tests

.drone.jsonnet
- The `grep` had a typo of `-e` instead of `-E` which made it not work
- Made the command actually fail the pipeline if unwanted linked libs
were found.
- Print in green if everything is okay.
- Add librt.so to the whitelist
=> Fix the static build linked libs output check

libabyss/src/http.cpp, llarp/config/config.cpp, llarp/config/ini.cpp, llarp/handlers/tun.cpp, llarp/util/str.hpp, test/util/test_llarp_util_str.cpp
It was a workaround for pre-C++17 std::string which didn't support
passing a string_view to various functions/operators.  There's only one
place left that needs an explicit conversion, and that's where it is
used as a map key; so just be explicit there and remove llarp::str()
everywhere else.
Edit: plus a workaround for ghc::filesystem::path for macos.
=> Remove llarp::str(string_view)

llarp/service/endpoint.cpp
when in 1 hop mode we where hitting a case where we were failing to build paths
this was because we were trying to diversify the endpoints used which is not
applicable in 1 hop mode because first hops are sticky. it was excluding the sticky first hops causing a build fail every time after initial path builds.
=> fix one hop mode path builds

daemon/main.cpp, include/llarp.h, include/llarp.hpp, llarp/config/key_manager.cpp, llarp/config/key_manager.hpp, llarp/context.cpp, llarp/dht/messages/gotrouter.cpp, llarp/router/abstractrouter.hpp, llarp/router/router.cpp, llarp/router/router.hpp, test/crypto/test_llarp_key_manager.cpp
This PR causes `router.cpp` to ignore our `self.signed` file if we're a client.
This was causing issues because `KeyManager` tries to do backups if `self.signed` is present and invalid. **We also need to figure out why these RCs are not passing validation.**
=> Dont touch self.signed if client

.drone.jsonnet
Static build runs on bionic, not focal.
=> Fix static distro drone typo in description

daemon/main.cpp, include/llarp.h, include/llarp.hpp, llarp/config/config.hpp, llarp/context.cpp, llarp/ev/vpnio.cpp, llarp/ev/vpnio.hpp, test/regress/2020-06-08-key-backup-bug.cpp
This removes most of the C API, which was acting as a mostly redundant.
Hive is broken on this branch, but can be addressed in #1312.
=> Remove [most of] C API

llarp/CMakeLists.txt, llarp/config/config.cpp, llarp/config/config.hpp, llarp/config/definition.hpp, llarp/dns/dns.hpp, llarp/dns/message.cpp, llarp/dns/message.hpp, llarp/dns/srv_data.cpp, llarp/dns/srv_data.hpp, llarp/handlers/tun.cpp, llarp/service/endpoint.cpp, llarp/service/endpoint.hpp, llarp/service/endpoint_state.cpp, llarp/service/endpoint_state.hpp, llarp/service/intro_set.cpp, llarp/service/intro_set.hpp, llarp/service/outbound_context.hpp, llarp/util/str.cpp, llarp/util/str.hpp
Service operators can now provide SRV records via the ini file.
To do so, in the [network] section add one or more lines with the following syntax:
`srv=_service._protocol priority weight port [target]`
Target must be omitted, a single dot `.`, or a valid name with .loki or .snode as the TLD.
.snode is allowed as this is meant to be used later for relays' router contact info.
Can squash upon request
=> SRV Record handling for introsets

llarp/service/endpoint.cpp, llarp/service/endpoint.hpp, llarp/service/endpoint_state.hpp, llarp/service/endpoint_types.hpp
remove locks and use lockless queues to remove lock contention.
this yields a massive speedup in mainloop thread. before it was eating 100% cpu at 3200KBps, now it is at about 54% at same speeds.
=> remove locks

daemon/main.cpp, vendor/libtuntap-master/tuntap-windows.c
by relocating to (`$PROGRAMDATA/.lokinet`)
- oops forgot to eat my own command line args
- fix DNS client configuration at startup
=> allow running lokinet as root on windows

.drone.jsonnet
- Disable bionic arm64 job to reduce the load on the ARM box a bit.
- Add bionic amd64 build so that we have a (normal) build on bionic.
- Remove sid/g++-10 job because g++ is now the default on sid (so the
debian/sid build is already doing the same thing).
=> Drone CI job shuffling

daemon/CMakeLists.txt
The debs don't want it (and so this will save needing to patch it out),
nor do you need it if running via a systemd service file that sets the
capabilities.
=> Allow -DWITH_SETCAP=OFF to disable setcap during make install

llarp/config/config.cpp, test/service/test_llarp_service_identity.cpp
The debs in 0.7 hack a `[dns] no-resolvconf=1` setting into the config file (commented out by default) that a user can use to disable the service file's invocation of resolvconf to update DNS settings.
lokinet 0.8 no longer allows unknown options, so this adds it into the config as a do-nothing option to let that setting still be used by init scripts.
Also contains a fix for the `upstream` comment not being written to generated files, and a test suite fix.
=> Support [dns] no-resolvconf option (ignored by lokinet) for deb compatibility

contrib/py/keygen/.gitignore, contrib/py/keygen/keygen.py, contrib/py/keygen/readme.md, llarp/router_contact.cpp, llarp/router_contact.hpp, llarp/service/identity.cpp, llarp/service/identity.hpp
* don't serialize ephemeral members of service identity so that generating keyfiles is easier
* generate ephemeral members of service identity
* add a keygen python script that generates hidden service keyfiles
=> dont serialize ephemeral members of service identity

llarp/config/config.cpp
0.7 supported both public-address and public-ip, but only the former was
being allowed in 0.8.
This makes `public-ip=...` work again, and makes it the canonical option
(because it makes a bit more sense than address when we also have the
public-port parameter), while making `public-address=` accepted with a
deprecation warning.
Also adds default descriptions for port and ip for the generated ini.
=> Make public-ip option work

CROSSCOMPILE.md
for 0.8 windows 8.1+ is practically enforced by ci
windows pre-8 can work but can't be automated
=> move old stuff down a notch
